"""Initial migration

Revision ID: 44174ab49f28
Revises: 
Create Date: 2026-06-23 00:55:51.978693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44174ab49f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('confederation', sa.String(length=20), nullable=True),
    sa.Column('flag_url', sa.String(length=512), nullable=True),
    sa.Column('eliminated_at_round', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('stats_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_kickoff_utc'), ['kickoff_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_matchday'), ['matchday'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_status'), ['status'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('total_fantasy_points', sa.Integer(), nullable=False),
    sa.Column('selected_by_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('sportmonks_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_position'), ['position'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('supported_nation_id', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('country_rank', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('free_transfers_bank', sa.Integer(), nullable=False),
    sa.Column('manual_changes_matchday', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supported_nation_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('booster_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booster_type', sa.String(length=30), nullable=False),
    sa.Column('matchday_used', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'booster_type', name='uq_user_booster')
    )
    with op.batch_alter_table('booster_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booster_usages_user_id'), ['user_id'], unique=False)

    op.create_table('fantasy_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('budget_remaining', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('formation', sa.String(length=10), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('vice_captain_id', sa.Integer(), nullable=True),
    sa.Column('matchday_points', sa.Integer(), nullable=False),
    sa.Column('twelfth_man_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['twelfth_man_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vice_captain_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'matchday', name='uq_user_matchday_team')
    )
    with op.batch_alter_table('fantasy_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_teams_matchday'), ['matchday'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_teams_user_id'), ['user_id'], unique=False)

    op.create_table('mini_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mini_leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mini_leagues_code'), ['code'], unique=True)

    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheet', sa.Boolean(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('penalty_saved', sa.Integer(), nullable=False),
    sa.Column('penalty_missed', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('chances_created', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('goals_outside_box', sa.Integer(), nullable=False),
    sa.Column('is_potm', sa.Boolean(), nullable=False),
    sa.Column('fantasy_points', sa.Integer(), nullable=False),
    sa.Column('scouting_bonus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'fixture_id', name='uq_player_fixture')
    )
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_stats_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_player_id'), ['player_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_out_id', sa.Integer(), nullable=True),
    sa.Column('player_in_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('cost_in_points', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_in_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_matchday'), ['matchday'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_user_id'), ['user_id'], unique=False)

    op.create_table('fantasy_team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_starting', sa.Boolean(), nullable=False),
    sa.Column('bench_order', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('matchday_points', sa.Integer(), nullable=False),
    sa.Column('removed_from_xi_matchday', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fantasy_team_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_team_players_fantasy_team_id'), ['fantasy_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_team_players_player_id'), ['player_id'], unique=False)

    op.create_table('mini_league_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('last_week_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['mini_leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_league_user')
    )
    with op.batch_alter_table('mini_league_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mini_league_standings_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mini_league_standings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mini_league_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mini_league_standings_user_id'))
        batch_op.drop_index(batch_op.f('ix_mini_league_standings_league_id'))

    op.drop_table('mini_league_standings')
    with op.batch_alter_table('fantasy_team_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fantasy_team_players_player_id'))
        batch_op.drop_index(batch_op.f('ix_fantasy_team_players_fantasy_team_id'))

    op.drop_table('fantasy_team_players')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_user_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_matchday'))

    op.drop_table('transfers')
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_fixture_id'))

    op.drop_table('player_match_stats')
    with op.batch_alter_table('mini_leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mini_leagues_code'))

    op.drop_table('mini_leagues')
    with op.batch_alter_table('fantasy_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fantasy_teams_user_id'))
        batch_op.drop_index(batch_op.f('ix_fantasy_teams_matchday'))

    op.drop_table('fantasy_teams')
    with op.batch_alter_table('booster_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booster_usages_user_id'))

    op.drop_table('booster_usages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_position'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_country_id'))

    op.drop_table('players')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_status'))
        batch_op.drop_index(batch_op.f('ix_fixtures_stage'))
        batch_op.drop_index(batch_op.f('ix_fixtures_matchday'))
        batch_op.drop_index(batch_op.f('ix_fixtures_kickoff_utc'))

    op.drop_table('fixtures')
    op.drop_table('countries')
    # ### end Alembic commands ###
